#!/bin/bash
# Arguments = -u http://brain-geek.github.com/ -c 10 -p 3

usage()
{
cat << EOF
usage: $0 options

  8..8
 (----)
( >__< )
 ^^~~^^

This script runs the Toad website load testing project.

OPTIONS:
   -h      Show this message
   -u      URL to start crawling
   -c      Number of browsers per process (default - 5)
   -p      Number of processes (default - 1)
   -o      Directory for logs (default - logs disabled)
   -t      Load for period of time, seconds (default - no limit)
EOF
}

URL=
CONCURRENCY=5
PROCESSES=1
LOG_DIR=
TOAD_PATH=./toad-bin
TIMER=0

while getopts “hc:p:u:o:t:” OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         u)
             URL=$OPTARG
             ;;
         c)
             CONCURRENCY=$OPTARG
             ;;
         p)
             PROCESSES=$OPTARG
             ;;
         o)
             LOG_DIR=$OPTARG
             ;;
         b)
             TOAD_PATH=$OPTARG
             ;;
         t)
             TIMER=$OPTARG
             ;;
         ?)
             usage
             exit
             ;;
     esac
done

TOAD_BNAME=$(basename $TOAD_PATH)

if [[ -z $URL ]]
then
     usage
     exit 1
fi

if [[ $LOG_DIR ]]; then
  mkdir -p $(dirname $LOG_DIR)
fi

#starting PROCESSES - 1 toads in background!
let PROCESSES--

for i in $(seq $PROCESSES); do
  if [[ $LOG_DIR ]]; then
     $TOAD_PATH $URL $CONCURRENCY $TIMER $LOG_DIR-$i &
  else
     $TOAD_PATH $URL $CONCURRENCY $TIMER &
  fi
done

if [[ $LOG_DIR ]]; then
   $TOAD_PATH $URL $CONCURRENCY $TIMER $LOG_DIR-0
else
   $TOAD_PATH $URL $CONCURRENCY $TIMER
fi

killall $TOAD_BNAME
